[General]
network = DumbbellNetwork

sim-time-limit = 10s

**.cmdenv-log-level = info



# Source- & Sink-Apps
*.deviceSource[*].numApps = 1
*.deviceSink1.numApps = 6

*.deviceSource[*].app[0].typename = "UdpSourceApp"
*.deviceSink1.app[*].typename = "UdpSinkApp"

*.deviceSource[*].app[0].io.destAddress = "deviceSink1"

*.deviceSource[*].app[0].display-name = "Source" + string(ancestorIndex(1))
*.deviceSink1.app[*].display-name = "Sink" + string(ancestorIndex(0))

*.deviceSource[*].app[0].io.destPort = 1000 + ancestorIndex(2)
*.deviceSink1.app[*].io.localPort = 1000 + ancestorIndex(1)

*.switch*.hasOutgoingStreams = true

# System Definitions
*.*.eth[*].bitrate = 100Mbps

*.deviceSource[*].app[0].source.packetLength = 1000B - 46B # 1000B overall pkt length incl. headers (8B UDP, 20B IPv4, 18B MAC)

## Streams
*.deviceSink1.app[0].io.displayStringTextFormat = "{numReceived} Stream-(7)-(0)"
*.deviceSink1.app[1].io.displayStringTextFormat = "{numReceived} Stream-(6)-(1)"
*.deviceSink1.app[2].io.displayStringTextFormat = "{numReceived} Stream-(5)-(2)"
*.deviceSink1.app[3].io.displayStringTextFormat = "{numReceived} Stream-(4)-(3)"
*.deviceSink1.app[4].io.displayStringTextFormat = "{numReceived} Stream-(3)-(4)"
*.deviceSink1.app[5].io.displayStringTextFormat = "{numReceived} Stream-(2)-(5)"

*.deviceSource[0].app[0].io.displayStringTextFormat = "{numSent} Stream-(7)-(0)"
*.deviceSource[1].app[0].io.displayStringTextFormat = "{numSent} Stream-(6)-(1)"
*.deviceSource[2].app[0].io.displayStringTextFormat = "{numSent} Stream-(5)-(2)"
*.deviceSource[3].app[0].io.displayStringTextFormat = "{numSent} Stream-(4)-(3)"
*.deviceSource[4].app[0].io.displayStringTextFormat = "{numSent} Stream-(3)-(4)"
*.deviceSource[5].app[0].io.displayStringTextFormat = "{numSent} Stream-(2)-(5)"

*.switch*.bridging.streamIdentifier.identifier.mapping = [
	{stream: "Stream-(7)-(0)", packetFilter: expr(udp.destPort == 1000)}, 
	{stream: "Stream-(6)-(1)", packetFilter: expr(udp.destPort == 1001)},
	{stream: "Stream-(5)-(2)", packetFilter: expr(udp.destPort == 1002)}, 
	{stream: "Stream-(4)-(3)", packetFilter: expr(udp.destPort == 1003)}, 
	{stream: "Stream-(3)-(4)", packetFilter: expr(udp.destPort == 1004)}, 
	{stream: "Stream-(2)-(5)", packetFilter: expr(udp.destPort == 1005)}]

*.deviceSource[0].app[0].source.productionInterval = 1000us
*.deviceSource[1].app[0].source.productionInterval = 1200us
*.deviceSource[2].app[0].source.productionInterval = 2000us
*.deviceSource[3].app[0].source.productionInterval = 1800us
*.deviceSource[4].app[0].source.productionInterval = 2500us
*.deviceSource[5].app[0].source.productionInterval = 2500us

*.deviceSource[0].app[0].source.startTime = 0us
*.deviceSource[1].app[0].source.startTime = 0us
*.deviceSource[2].app[0].source.startTime = 0us
*.deviceSource[3].app[0].source.startTime = 0us
*.deviceSource[4].app[0].source.startTime = 0us
*.deviceSource[5].app[0].source.startTime = 500us



# PIFOCD configurations
*.switch1.eth[2].macLayer.queue.typename = "SchedulingTreeQueue"
*.switch2.eth[2].macLayer.queue.typename = "SchedulingTreeQueue"
*.switch3.eth[2].macLayer.queue.typename = "SchedulingTreeQueue"
*.switch4.eth[1].macLayer.queue.typename = "SchedulingTreeQueue"


*.switch*.eth[*].macLayer.queue.useRgpProtocol = true
*.switch*.eth[*].macLayer.queue.flowCount = 6
*.switch*.eth[*].macLayer.queue.periods = [1000, 1200, 2000, 1800, 2500, 2500]

# This is automatically set on the first hop and the first packet
*.switch*.eth[*].macLayer.queue.phases = [0, 0, 0, 0, 0 ,500]

# Accumulated delays at each hop per flow
# Stream-(7 = [pcp])-(0 = [id])
# 80 us transmission delay, 0us propagation delay since length of links is 0
*.switch1.eth[2].macLayer.queue.accumulatedDelays = [1*80, 1*80, 1*80, 0, 0, 0]
*.switch2.eth[2].macLayer.queue.accumulatedDelays = [0, 0, 0, 1*80, 1*80, 1*80]
*.switch3.eth[2].macLayer.queue.accumulatedDelays = [2*80 + 261, 2*80 + 469, 2*80 + 591, 2*80 + 252, 2*80 + 434, 2*80 + 539]
*.switch4.eth[1].macLayer.queue.accumulatedDelays = [3*80 + 261 + 261, 3*80 + 469 + 469, 3*80 + 591 + 689, 3*80 + 252 + 937, 3*80 + 434 + 1195, 3*80 + 539 + 1362]



# Display number of packets sent and received on network nodes
*.visualizer.infoVisualizer.displayInfos = true
*.visualizer.infoVisualizer.placementHint = "top"
*.visualizer.infoVisualizer.modules = "*.*.app[*].io"
*.visualizer.networkNodeVisualizer.annotationSpacing = 12


