[General]
network = DumbbellNetwork

sim-time-limit = 10s

**.cmdenv-log-level = info

*.*.eth[*].bitrate = 100Mbps

# SourceApps
*.deviceSource*.numApps = 1
*.deviceSource*.app[0].typename = "UdpSourceApp"
*.deviceSource1.app[0].display-name = "Source1"
*.deviceSource2.app[0].display-name = "Source2"
*.deviceSource1.app[0].io.destAddress = "deviceSink1"
*.deviceSource2.app[0].io.destAddress = "deviceSink2"
*.deviceSource1.app[0].io.destPort = 1000
*.deviceSource2.app[0].io.destPort = 1001
*.deviceSource1.app[0].io.displayStringTextFormat = "{numSent} Stream1"
*.deviceSource2.app[0].io.displayStringTextFormat = "{numSent} Stream2"
*.deviceSource*.app[0].source.packetLength = 1000B - 46B # 1000B overall pkt length incl. headers (8B UDP, 20B IPv4, 18B MAC)

*.deviceSource1.app[0].source.productionInterval = truncnormal(150us, 20us) 
*.deviceSource2.app[0].source.productionInterval = truncnormal(200us, 20us) # Both streams together reach around ~93.3Mbps
# *.deviceSource*.app[0].source.productionInterval = 200us 


# SinkApps
*.deviceSink*.numApps = 1
*.deviceSink*.app[0].typename = "UdpSinkApp"
*.deviceSink1.app[0].display-name = "Sink1"
*.deviceSink2.app[0].display-name = "Sink2"
*.deviceSink1.app[0].io.localPort = 1000
*.deviceSink2.app[0].io.localPort = 1001
*.deviceSink1.app[0].io.displayStringTextFormat = "{numReceived} Stream1"
*.deviceSink2.app[0].io.displayStringTextFormat = "{numReceived} Stream2"

# Display number of packets sent and received on network nodes
*.visualizer.infoVisualizer.displayInfos = true
*.visualizer.infoVisualizer.placementHint = "top"
*.visualizer.infoVisualizer.modules = "*.*.app[*].io"
*.visualizer.networkNodeVisualizer.annotationSpacing = 12

# PIFOCD configurations
*.switch1.eth[2].macLayer.queue.typename = "SchedulingTreeQueue"

*.switch1.hasOutgoingStreams = true
*.switch1.bridging.streamIdentifier.identifier.mapping = [
	{stream: "A0", packetFilter: expr(udp.destPort == 1000)}, 
	{stream: "B1", packetFilter: expr(udp.destPort == 1001)}]

