[General]
network = DumbbellNetwork

sim-time-limit = 10s

**.cmdenv-log-level = info

*.switch*.hasOutgoingStreams = true


# PIFOCD configurations
*.switch1.eth[2].macLayer.queue.typename = "SchedulingTreeQueue"
*.switch2.eth[2].macLayer.queue.typename = "SchedulingTreeQueue"
*.switch3.eth[2].macLayer.queue.typename = "SchedulingTreeQueue"
*.switch4.eth[1].macLayer.queue.typename = "SchedulingTreeQueue"

# Display number of packets sent and received on network nodes
*.visualizer.infoVisualizer.displayInfos = true
*.visualizer.infoVisualizer.placementHint = "top"
*.visualizer.infoVisualizer.modules = "*.*.app[*].io"
*.visualizer.networkNodeVisualizer.annotationSpacing = 12


# Replace bellow with a configuration
[Config similar_pcps]
*.switch*.eth[*].macLayer.queue.useRgpProtocol = false
*.*.eth[*].bitrate = 100Mbps

# Source- & Sink-Apps
*.deviceSink1.numApps = 6
*.deviceSource[0].numApps = 1
*.deviceSource[1].numApps = 1
*.deviceSource[2].numApps = 1
*.deviceSource[3].numApps = 1
*.deviceSource[4].numApps = 1
*.deviceSource[5].numApps = 1

*.deviceSource[*].app[*].typename = "UdpSourceApp"
*.deviceSink1.app[*].typename = "UdpSinkApp"

*.deviceSource[*].app[*].io.destAddress = "deviceSink1"

*.deviceSource[0].app[0].display-name = "Source0 (0)"
*.deviceSink1.app[0].display-name = "Sink0"
*.deviceSource[1].app[0].display-name = "Source1 (0)"
*.deviceSink1.app[1].display-name = "Sink1"
*.deviceSource[2].app[0].display-name = "Source2 (0)"
*.deviceSink1.app[2].display-name = "Sink2"
*.deviceSource[3].app[0].display-name = "Source3 (0)"
*.deviceSink1.app[3].display-name = "Sink3"
*.deviceSource[4].app[0].display-name = "Source4 (0)"
*.deviceSink1.app[4].display-name = "Sink4"
*.deviceSource[5].app[0].display-name = "Source5 (0)"
*.deviceSink1.app[5].display-name = "Sink5"

*.deviceSource[0].app[0].io.destPort = 1000
*.deviceSink1.app[0].io.localPort = 1000
*.deviceSource[1].app[0].io.destPort = 1001
*.deviceSink1.app[1].io.localPort = 1001
*.deviceSource[2].app[0].io.destPort = 1002
*.deviceSink1.app[2].io.localPort = 1002
*.deviceSource[3].app[0].io.destPort = 1003
*.deviceSink1.app[3].io.localPort = 1003
*.deviceSource[4].app[0].io.destPort = 1004
*.deviceSink1.app[4].io.localPort = 1004
*.deviceSource[5].app[0].io.destPort = 1005
*.deviceSink1.app[5].io.localPort = 1005

*.deviceSource[0].app[0].source.packetLength = 1000B - 46B # 1000B overall pkt length incl. headers (8B UDP, 20B IPv4, 18B MAC)
*.deviceSource[1].app[0].source.packetLength = 1000B - 46B # 1000B overall pkt length incl. headers (8B UDP, 20B IPv4, 18B MAC)
*.deviceSource[2].app[0].source.packetLength = 1000B - 46B # 1000B overall pkt length incl. headers (8B UDP, 20B IPv4, 18B MAC)
*.deviceSource[3].app[0].source.packetLength = 1000B - 46B # 1000B overall pkt length incl. headers (8B UDP, 20B IPv4, 18B MAC)
*.deviceSource[4].app[0].source.packetLength = 1000B - 46B # 1000B overall pkt length incl. headers (8B UDP, 20B IPv4, 18B MAC)
*.deviceSource[5].app[0].source.packetLength = 1000B - 46B # 1000B overall pkt length incl. headers (8B UDP, 20B IPv4, 18B MAC)

## Streams
*.deviceSink1.app[0].io.displayStringTextFormat = "{numReceived} Stream-(7)-(0)"
*.deviceSink1.app[1].io.displayStringTextFormat = "{numReceived} Stream-(6)-(1)"
*.deviceSink1.app[2].io.displayStringTextFormat = "{numReceived} Stream-(6)-(2)"
*.deviceSink1.app[3].io.displayStringTextFormat = "{numReceived} Stream-(7)-(3)"
*.deviceSink1.app[4].io.displayStringTextFormat = "{numReceived} Stream-(6)-(4)"
*.deviceSink1.app[5].io.displayStringTextFormat = "{numReceived} Stream-(5)-(5)"

*.deviceSource[0].app[0].io.displayStringTextFormat = "{numSent} Stream-(7)-(0)"
*.deviceSource[1].app[0].io.displayStringTextFormat = "{numSent} Stream-(6)-(1)"
*.deviceSource[2].app[0].io.displayStringTextFormat = "{numSent} Stream-(6)-(2)"
*.deviceSource[3].app[0].io.displayStringTextFormat = "{numSent} Stream-(7)-(3)"
*.deviceSource[4].app[0].io.displayStringTextFormat = "{numSent} Stream-(6)-(4)"
*.deviceSource[5].app[0].io.displayStringTextFormat = "{numSent} Stream-(5)-(5)"

*.switch*.bridging.streamIdentifier.identifier.mapping = [
	{stream: "Stream-(7)-(0)", packetFilter: expr(udp.destPort == 1000)},
	{stream: "Stream-(6)-(1)", packetFilter: expr(udp.destPort == 1001)},
	{stream: "Stream-(6)-(2)", packetFilter: expr(udp.destPort == 1002)},
	{stream: "Stream-(7)-(3)", packetFilter: expr(udp.destPort == 1003)},
	{stream: "Stream-(6)-(4)", packetFilter: expr(udp.destPort == 1004)},
	{stream: "Stream-(5)-(5)", packetFilter: expr(udp.destPort == 1005)}]


*.deviceSource[0].app[0].source.productionInterval = 1100us
*.deviceSource[1].app[0].source.productionInterval = 2000us
*.deviceSource[2].app[0].source.productionInterval = 2000us
*.deviceSource[3].app[0].source.productionInterval = 1800us
*.deviceSource[4].app[0].source.productionInterval = 2500us
*.deviceSource[5].app[0].source.productionInterval = 2500us

*.deviceSource[0].app[0].source.startTime = 0us
*.deviceSource[1].app[0].source.startTime = 0us
*.deviceSource[2].app[0].source.startTime = 0us
*.deviceSource[3].app[0].source.startTime = 0us
*.deviceSource[4].app[0].source.startTime = 0us
*.deviceSource[5].app[0].source.startTime = 0us


*.switch*.eth[*].macLayer.queue.flowCount = 6
*.switch*.eth[*].macLayer.queue.periods = [1100, 2000, 2000, 1800, 2500, 2500]
*.switch*.eth[*].macLayer.queue.phases = [0, 0, 0, 0, 0, 0]

*.switch1.eth[2].macLayer.queue.accumulatedDelays = [1*80, 1*80, 1*80, 0, 0, 0]
*.switch2.eth[2].macLayer.queue.accumulatedDelays = [0, 0, 0, 1*80, 1*80, 1*80]
*.switch3.eth[2].macLayer.queue.accumulatedDelays = [2*80 + 173, 2*80 + 284, 2*80 + 284, 2*80 + 168, 2*80 + 260, 2*80 + 270]
*.switch4.eth[1].macLayer.queue.accumulatedDelays = [3*80 + 173 + 272, 3*80 + 284 + 623, 3*80 + 284 + 623, 3*80 + 168 + 272, 3*80 + 260 + 623, 3*80 + 270 + 650]
